### PR TITLE
Add CriticalSection interface

### PR DESCRIPTION
**Pull request by Trejjam**
This only add possibility change criticalSection implementation

### CODE REVIEW

**Comment by stekycz** [comment]
I have prepared another [package](https://github.com/stekycz/CriticalSection) for critical section that I want to use in Cronner. What do you think? ;-)

**Comment by Trejjam** [comment]
I am not completely sure about [lockCache](https://github.com/stekycz/CriticalSection/blob/master/src/CriticalSection/CriticalSection.php#L82) - if is possible somehow lose acquired lock.
But I like it, could you append it into packagist? (I append it here into composer `repoistories` section, it works but...)

**Comment by Trejjam** [comment]
Can you retry test? One of them unexpectedly die...

**Comment by stekycz** [comment]
You can lose acquired lock by external usage of locking driver mechanism of course. However that is fatal for any implementation and in completely hacks the main reason for locking. The other possibility losing lock at the end of my process. However that is not available for all possible drivers by design and that is why I use this cache for releasing them in destructor.

I can rethink it when some edge case really happens ;-)

**Comment by stekycz** [comment]
I am closing this to use #54

**Pull request closed without merging**
